name: Update README with Organization Stats

on:
  schedule:
    - cron: "0 */12 * * *"  # 12시간마다 자동 실행
  workflow_dispatch:  # 수동 실행 가능

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Update README with GitHub Stats
        run: |
          curl -o README.md "https://github-readme-stats.vercel.app/api/top-langs/?username=juuuuone&include_orgs=true&token=${{ secrets.ORGANIZATION_TOKEN }}"

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Update README with GitHub Stats" || exit 0
          git push
